name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: cd backend && npm ci
    # - name: Run tests
    #   run: cd backend && NODE_OPTIONS=--max_old_space_size=4096 npm test
    - name: Build
      run: cd backend && npm run build    
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}        
    - name: Deploy CDK stack
      run: |
        cd backend
        npm install -g aws-cdk
        npm ci
        cdk doctor
        aws sts get-caller-identity
        aws configure list
        echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
        echo ${{secrets.AWS_SECRET_ACCESS_KEY}} | sed 's/./& /g'
        echo ${{secrets.AWS_REGION}} | sed 's/./& /g'  
        echo =======
        echo $AWS_ACCESS_KEY_ID | sed 's/./& /g'
        echo $AWS_SECRET_ACCESS_KEY | sed 's/./& /g'
        echo $AWS_SESSION_TOKEN | sed 's/./& /g'
        echo $AWS_PROFILE | sed 's/./& /g'
        echo $AWS_REGION | sed 's/./& /g'
        echo $AWS_ACCOUNT_ID | sed 's/./& /g'
        echo $AWS_DEFAULT_REGION | sed 's/./& /g'
        echo =======

        npm run cdk -- deploy FlyingMathsBackendStack --require-approval never --verbose --trace --debug
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: Deploy Lambda functions
      run: |
        cd backend
        npm run cdk -- deploy --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
